services:
  Aligent\DBToolsBundle\Command\AbstractCommand:
    class: Aligent\DBToolsBundle\Command\AbstractCommand
    calls:
      - [setDatabaseHelper, ['@aligent_db_tools.helper.database']]

  Aligent\DBToolsBundle\Command\ConsoleCommand:
    parent: Aligent\DBToolsBundle\Command\AbstractCommand
    class: Aligent\DBToolsBundle\Command\ConsoleCommand
    public: false
    tags:
      - { name: console.command }

  Aligent\DBToolsBundle\Command\CreateCommand:
    parent: Aligent\DBToolsBundle\Command\AbstractCommand
    class: Aligent\DBToolsBundle\Command\CreateCommand
    public: false
    tags:
      - { name: console.command }

  Aligent\DBToolsBundle\Command\DropCommand:
    parent: Aligent\DBToolsBundle\Command\AbstractCommand
    class: Aligent\DBToolsBundle\Command\DropCommand
    public: false
    tags:
      - { name: console.command }

  Aligent\DBToolsBundle\Command\DumpCommand:
    parent: Aligent\DBToolsBundle\Command\AbstractCommand
    class: Aligent\DBToolsBundle\Command\DumpCommand
    public: false
    tags:
      - { name: console.command }

  Aligent\DBToolsBundle\Command\ImportCommand:
    parent: Aligent\DBToolsBundle\Command\AbstractCommand
    class: Aligent\DBToolsBundle\Command\ImportCommand
    public: false
    tags:
      - { name: console.command }

  Aligent\DBToolsBundle\Command\InfoCommand:
    parent: Aligent\DBToolsBundle\Command\AbstractCommand
    class: Aligent\DBToolsBundle\Command\InfoCommand
    public: false
    tags:
      - { name: console.command }

  Aligent\DBToolsBundle\Command\QueryCommand:
    parent: Aligent\DBToolsBundle\Command\AbstractCommand
    class: Aligent\DBToolsBundle\Command\QueryCommand
    public: false
    tags:
      - { name: console.command }
