parameters:
  aligent_db_tools.parameters.yml: '%kernel.root_dir%/config/parameters.yml'

services:
  aligent_db_tools.helper.db_settings:
    class: 'Aligent\DBToolsBundle\Helper\DBSettings'
    arguments:
        - '%aligent_db_tools.parameters.yml%'
  aligent_db_tools.helper.database:
    public: true
    class: 'Aligent\DBToolsBundle\Helper\DatabaseHelper'
    arguments:
        - '@aligent_db_tools.helper.db_settings'
  aligent_db_tools.helper.compressor.gzip:
    public: true
    class: 'Aligent\DBToolsBundle\Helper\Compressor\Gzip'
  aligent_db_tools.helper.compressor.uncompressed:
    public: true
    class: 'Aligent\DBToolsBundle\Helper\Compressor\Uncompressed'
