aligent_db_tools:
  definitions:
    oro_commerce:
      truncate:
        standard:
          - oro_message_queue_state
          - oro_message_queue_job_unique
          - oro_message_queue_job
          - oro_message_queue
          - oro_cus_navigation_history
          - oro_navigation_history
          - oro_tracking_data
          - oro_tracking_unique_visit
          - oro_tracking_visit_event
          - oro_search_index_text
          - oro_search_index_integer
          - oro_search_index_decimal
          - oro_search_index_decimal
        cascade:
          - oro_audit
          - oro_tracking_event
          - oro_tracking_event_dictionary
          - oro_tracking_visit
          - oro_tracking_website
          - oro_search_item
      update:
        oro_address:
          - { column: street, function: md5 }
          - { column: city, function: md5 }
          - { column: postal_code, function: md5 }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
        oro_business_unit:
          - { column: email, function: email }
          - { column: name, function: md5 }
          - { column: phone, function: md5 }
        oro_comment:
          - { column: message, function: md5 }
        oro_customer:
          - { column: name, function: md5 }
        oro_customer_address:
          - { column: street, function: md5 }
          - { column: city, function: md5 }
          - { column: postal_code, function: md5 }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
        oro_customer_user:
          - { column: username, function: email }
          - { column: email, function: email }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
          - { column: password, function: password }
        oro_customer_user_address:
          - { column: street, function: md5 }
          - { column: city, function: md5 }
          - { column: postal_code, function: md5 }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
        oro_email:
          - { column: subject, function: md5 }
          - { column: from_name, function: md5 }
        oro_email_origin:
          - { column: imap_host, function: md5 }
          - { column: imap_user, function: md5 }
        oro_email_address:
          - { column: email, function: email }
        oro_email_body:
          - { column: body, function: md5 }
          - { column: text_body, function: md5 }
        oro_email_attachment_content:
          - { column: content, function: attachment }
        oro_email_recipient:
          - { column: name, function: md5 }
        oro_integration_transport:
          - { column: api_key, function: md5 }
          - { column: api_user, function: md5 }
          - { column: api_token, function: md5 }
        oro_notification_mass_notif:
          - { column: email, function: email }
          - { column: sender, function: md5 }
        oro_notification_recip_list:
          - { column: email, function: email }
          - { column: entity_emails, function: md5 }
        oro_note:
          - { column: message, function: md5 }
        oro_order_address:
          - { column: street, function: md5 }
          - { column: city, function: md5 }
          - { column: postal_code, function: md5 }
          - { column: phone, function: md5 }
        oro_order_shipping_tracking:
          - { column: number, function: md5 }
        oro_payment_transaction:
          - { column: access_identifier, function: md5 }
          - { column: access_token, function: md5 }
        oro_pro_user_client_data:
          - { column: ip_address, function: md5 }
        oro_pro_user_password_history:
          - { column: salt, function: password }
          - { column: password_hash, function: password }
        oro_quote_address:
          - { column: street, function: md5 }
          - { column: city, function: md5 }
          - { column: postal_code, function: md5 }
          - { column: phone, function: md5 }
        oro_rfp_request:
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
          - { column: email, function: email }
          - { column: phone, function: md5 }
        oro_user:
          - { column: username, function: email }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
          - { column: email, function: email }
          - { column: phone, function: md5 }
          - { column: birthday, function: date }
          - { column: salt, function: password }
          - { column: password, function: password }
        oro_user_impersonation:
          - { column: token, function: md5 }
          - { column: ip_address, function: md5 }
        oro_user_email:
          - { column: email, function: email }
        oro_user_api:
          - { column: api_key, function: md5 }
        orocrm_call:
          - { column: phone_number, function: md5 }
        orocrm_campaign_email:
          - { column: transport, function: md5 }
          - { column: sender_email, function: md5 }
          - { column: name, function: md5 }
        orocrm_contact:
          - { column: email, function: email }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
          - { column: birthday, function: date }
          - { column: fax, function: md5 }
          - { column: skype, function: md5 }
          - { column: twitter, function: md5 }
          - { column: facebook, function: md5 }
          - { column: linkedin, function: md5 }
        orocrm_contact_address:
          - { column: street, function: md5 }
          - { column: city, function: md5 }
          - { column: postal_code, function: md5 }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
        orocrm_contactus_request:
          - { column: email_address, function: email }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
          - { column: phone, function: md5 }
        orocrm_contact_phone:
          - { column: phone, function: md5 }
        orocrm_contact_email:
          - { column: email, function: email }
        orocrm_dm_contact:
          - { column: email, function: email }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
          - { column: postcode, function: md5 }
        orocrm_magento_cart:
          - { column: email, function: email }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
        orocrm_magento_cart_address:
          - { column: phone, function: md5 }
          - { column: street, function: md5 }
          - { column: city, function: md5 }
          - { column: postal_code, function: md5 }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
        orocrm_magento_customer:
          - { column: email, function: email }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
          - { column: birthday, function: date }
          - { column: password, function: password }
        orocrm_magento_customer_addr:
          - { column: phone, function: md5 }
          - { column: street, function: md5 }
          - { column: city, function: md5 }
          - { column: postal_code, function: md5 }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
        orocrm_magento_newsl_subscr:
          - { column: email, function: email }
        orocrm_magento_order:
          - { column: customer_email, function: email }
          - { column: remote_ip, function: md5 }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
        orocrm_magento_order_address:
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
          - { column: phone, function: md5 }
          - { column: fax, function: md5 }
          - { column: street, function: md5 }
          - { column: city, function: md5 }
          - { column: postal_code, function: md5 }
        orocrm_mailchimp_campaign:
          - { column: from_email, function: email }
          - { column: from_name, function: md5 }
        orocrm_mailchimp_member:
          - { column: email, function: email }
          - { column: phone, function: md5 }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
          - { column: confirmed_ip, function: md5 }
        orocrm_mailchimp_ml_email:
          - { column: email, function: email }
        orocrm_mc_mmbr_activity:
          - { column: email, function: email }
          - { column: ip_address, function: md5 }
        orocrm_mc_subscribers_list:
          - { column: default_from_name, function: md5 }
          - { column: default_from_email, function: md5 }
        orocrm_sales_b2bcustomer_email:
          - { column: email, function: email }
        orocrm_sales_b2bcustomer_phone:
          - { column: phone, function: md5 }
        orocrm_sales_lead:
          - { column: name, function: md5 }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
          - { column: twitter, function: md5 }
          - { column: linkedin, function: md5 }
        orocrm_sales_lead_address:
          - { column: street, function: md5 }
          - { column: city, function: md5 }
          - { column: postal_code, function: md5 }
          - { column: first_name, function: md5 }
          - { column: last_name, function: md5 }
        orocrm_sales_lead_email:
          - { column: email, function: email }
        orocrm_sales_lead_phone:
          - { column: phone, function: md5 }
        orocrm_zd_user:
          - { column: email, function: email }